"""prevent duplicate room memberships

Revision ID: 94dc272fe837
Revises: b65d313e32e7
Create Date: 2026-09-23 00:55:03.965185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dc272fe837'
down_revision = 'b65d313e32e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_membership', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_room', ['user_id', 'room_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_membership', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_room', type_='unique')

    # ### end Alembic commands ###
